/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 2.0.0
 */
export type GetPagesParams = {
/**
 * Sort by attributes ascending (asc) or descending (desc)
 */
sort?: string;
/**
 * Return page/pageSize (default: true)
 */
'pagination[withCount]'?: boolean;
/**
 * Page number (default: 0)
 */
'pagination[page]'?: number;
/**
 * Page size (default: 25)
 */
'pagination[pageSize]'?: number;
/**
 * Offset value (default: 0)
 */
'pagination[start]'?: number;
/**
 * Number of entities to return (default: 25)
 */
'pagination[limit]'?: number;
/**
 * Fields to return (ex: title,author)
 */
fields?: string;
/**
 * Relations to return
 */
populate?: string;
/**
 * Filters to apply
 */
filters?: { [key: string]: any };
/**
 * Locale to apply
 */
locale?: string;
};

export interface SharedBannerTilesComponent {
  __component?: string;
  id?: number;
  teasers?: PrivatePageRelationComponent[];
}

export interface SharedBannerVideoComponent {
  __component?: string;
  description?: string;
  id?: number;
  title?: string;
  videoUrl?: string;
}

export interface SharedBannerCardsComponent {
  __component?: string;
  id?: number;
  teasers?: PrivatePageRelationComponent[];
}

export type PrivatePageRelationComponentPageDataAttributes = { [key: string]: any };

export type PrivatePageRelationComponentPageData = {
  attributes?: PrivatePageRelationComponentPageDataAttributes;
  id?: number;
};

export type PrivatePageRelationComponentPage = {
  data?: PrivatePageRelationComponentPageData;
};

export type PrivatePageRelationComponentColor = typeof PrivatePageRelationComponentColor[keyof typeof PrivatePageRelationComponentColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrivatePageRelationComponentColor = {
  Default: 'Default',
  Highlight: 'Highlight',
} as const;

export interface PrivatePageRelationComponent {
  Color?: PrivatePageRelationComponentColor;
  id?: number;
  page?: PrivatePageRelationComponentPage;
}

export type SharedHeaderComponentImageData = {
  attributes?: SharedHeaderComponentImageDataAttributes;
  id?: number;
};

export type SharedHeaderComponentImage = {
  data?: SharedHeaderComponentImageData;
};

export interface SharedHeaderComponent {
  __component?: string;
  buttons?: SharedButtonComponent[];
  id?: number;
  image?: SharedHeaderComponentImage;
  title?: string;
}

export type SharedHeaderComponentImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedHeaderComponentImageDataAttributesUpdatedByData = {
  attributes?: SharedHeaderComponentImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedHeaderComponentImageDataAttributesUpdatedBy = {
  data?: SharedHeaderComponentImageDataAttributesUpdatedByData;
};

export type SharedHeaderComponentImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedHeaderComponentImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedHeaderComponentImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedHeaderComponentImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedHeaderComponentImageDataAttributesProviderMetadata;
  related?: SharedHeaderComponentImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedHeaderComponentImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedHeaderComponentImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedHeaderComponentImageDataAttributesRelatedDataItem = {
  attributes?: SharedHeaderComponentImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedHeaderComponentImageDataAttributesRelated = {
  data?: SharedHeaderComponentImageDataAttributesRelatedDataItem[];
};

export type SharedHeaderComponentImageDataAttributesProviderMetadata = {};

export type SharedHeaderComponentImageDataAttributesFormats = {};

export type SharedHeaderComponentImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedHeaderComponentImageDataAttributesFolderData = {
  attributes?: SharedHeaderComponentImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedHeaderComponentImageDataAttributesFolder = {
  data?: SharedHeaderComponentImageDataAttributesFolderData;
};

export type SharedHeaderComponentImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedHeaderComponentImageDataAttributesCreatedByData = {
  attributes?: SharedHeaderComponentImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedHeaderComponentImageDataAttributesCreatedBy = {
  data?: SharedHeaderComponentImageDataAttributesCreatedByData;
};

export type SharedButtonComponentLinkData = {
  attributes?: SharedButtonComponentLinkDataAttributes;
  id?: number;
};

export type SharedButtonComponentLink = {
  data?: SharedButtonComponentLinkData;
};

export interface SharedButtonComponent {
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedButtonComponentImage;
  link?: SharedButtonComponentLink;
  title?: string;
}

export type SharedButtonComponentLinkDataAttributes = { [key: string]: any };

export type SharedButtonComponentImageData = {
  attributes?: SharedButtonComponentImageDataAttributes;
  id?: number;
};

export type SharedButtonComponentImage = {
  data?: SharedButtonComponentImageData;
};

export type SharedButtonComponentImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedButtonComponentImageDataAttributesUpdatedByData = {
  attributes?: SharedButtonComponentImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedButtonComponentImageDataAttributesUpdatedBy = {
  data?: SharedButtonComponentImageDataAttributesUpdatedByData;
};

export type SharedButtonComponentImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedButtonComponentImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedButtonComponentImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedButtonComponentImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedButtonComponentImageDataAttributesProviderMetadata;
  related?: SharedButtonComponentImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedButtonComponentImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedButtonComponentImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedButtonComponentImageDataAttributesRelatedDataItem = {
  attributes?: SharedButtonComponentImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedButtonComponentImageDataAttributesRelated = {
  data?: SharedButtonComponentImageDataAttributesRelatedDataItem[];
};

export type SharedButtonComponentImageDataAttributesProviderMetadata = {};

export type SharedButtonComponentImageDataAttributesFormats = {};

export type SharedButtonComponentImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedButtonComponentImageDataAttributesFolderData = {
  attributes?: SharedButtonComponentImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedButtonComponentImageDataAttributesFolder = {
  data?: SharedButtonComponentImageDataAttributesFolderData;
};

export type SharedButtonComponentImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedButtonComponentImageDataAttributesCreatedByData = {
  attributes?: SharedButtonComponentImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedButtonComponentImageDataAttributesCreatedBy = {
  data?: SharedButtonComponentImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributes = {
  content?: SharedBannerFullComponentLinkDataAttributesContentItem[];
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesCreatedBy;
  defaultHeader?: SharedBannerFullComponentLinkDataAttributesDefaultHeader;
  description?: string;
  locale?: string;
  localizations?: SharedBannerFullComponentLinkDataAttributesLocalizations;
  publishedAt?: string;
  slug?: string;
  teaserImage?: SharedBannerFullComponentLinkDataAttributesTeaserImage;
  title?: string;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesUpdatedBy;
};

export type SharedBannerFullComponentLinkData = {
  attributes?: SharedBannerFullComponentLinkDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLink = {
  data?: SharedBannerFullComponentLinkData;
};

export interface SharedBannerFullComponent {
  __component?: string;
  alignment?: SharedBannerFullComponentAlignment;
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedBannerFullComponentImage;
  link?: SharedBannerFullComponentLink;
  title?: string;
}

export type SharedBannerFullComponentLinkDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImage = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageData;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesLocalizationsDataItem = {};

export type SharedBannerFullComponentLinkDataAttributesLocalizations = {
  data?: SharedBannerFullComponentLinkDataAttributesLocalizationsDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesDefaultHeader = typeof SharedBannerFullComponentLinkDataAttributesDefaultHeader[keyof typeof SharedBannerFullComponentLinkDataAttributesDefaultHeader];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesDefaultHeader = {
  Visible: 'Visible',
  Hidden: 'Hidden',
} as const;

export type SharedBannerFullComponentLinkDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnine = {
  __component?: string;
  id?: number;
  teasers?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemPageDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemPageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemPageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemPage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemPageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemColor = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemColor[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemColor = {
  Default: 'Default',
  Highlight: 'Highlight',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItem = {
  Color?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemColor;
  id?: number;
  page?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnineTeasersItemPage;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixeight = {
  __component?: string;
  description?: string;
  id?: number;
  title?: string;
  videoUrl?: string;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemPageDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemPageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemPageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemPage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemPageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemColor = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemColor[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemColor = {
  Default: 'Default',
  Highlight: 'Highlight',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItem = {
  Color?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemColor;
  id?: number;
  page?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItemPage;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwo = {
  __component?: string;
  id?: number;
  teasers?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwoTeasersItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItem = SharedBannerFullComponentLinkDataAttributesContentItemAnyOf | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothree | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixtwo | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixeight | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSixnine;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothree = {
  __component?: string;
  buttons?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItem[];
  id?: number;
  image?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImage;
  title?: string;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItem = {
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImage;
  link?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemLink;
  title?: string;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemLinkDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemLinkData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemLinkDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemLink = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemLinkData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeButtonsItemImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLinkDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLinkData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLinkDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLink = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLinkData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOf = {
  __component?: string;
  alignment?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment;
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImage;
  link?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLink;
  title?: string;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment = {
  Left: 'Left',
  Middle: 'Middle',
  Right: 'Right',
} as const;

export type SharedBannerFullComponentImageData = {
  attributes?: SharedBannerFullComponentImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImage = {
  data?: SharedBannerFullComponentImageData;
};

export type SharedBannerFullComponentImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesRelated = {
  data?: SharedBannerFullComponentImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentImageDataAttributesFormats = {};

export type SharedBannerFullComponentImageDataAttributesFolder = {
  data?: SharedBannerFullComponentImageDataAttributesFolderData;
};

export type SharedBannerFullComponentImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesParentDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesParentData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesParentDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesParent = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesParentData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributes = {
  children?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildren;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedBy;
  files?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFiles;
  name?: string;
  parent?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesParent;
  path?: string;
  pathId?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedBy;
};

export type SharedBannerFullComponentImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesProviderMetadata;
  related?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFiles = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelated = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesProviderMetadata = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFormats = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolderData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolder = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolderData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributes = {
  blocked?: boolean;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy;
  email?: string;
  firstname?: string;
  isActive?: boolean;
  lastname?: string;
  preferedLanguage?: string;
  registrationToken?: string;
  resetPasswordToken?: string;
  roles?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy;
  username?: string;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsersDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsersDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsersDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsers = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsersDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributes = {
  code?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedBy;
  description?: string;
  name?: string;
  permissions?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissions;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedBy;
  users?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsers;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissions = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesProperties = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributes = {
  action?: string;
  actionParameters?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesActionParameters;
  conditions?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesConditions;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy;
  properties?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesProperties;
  role?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole;
  subject?: string;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesConditions = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesActionParameters = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildrenDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildrenDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildrenDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildren = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildrenDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentAlignment = typeof SharedBannerFullComponentAlignment[keyof typeof SharedBannerFullComponentAlignment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentAlignment = {
  Left: 'Left',
  Middle: 'Middle',
  Right: 'Right',
} as const;

export type PageResponseMeta = { [key: string]: any };

export interface Page {
  content?: PageContentItem[];
  createdAt?: string;
  createdBy?: PageCreatedBy;
  defaultHeader: PageDefaultHeader;
  description?: string;
  locale?: string;
  localizations?: PageLocalizations;
  publishedAt?: string;
  slug: string;
  teaserImage: PageTeaserImage;
  title: string;
  updatedAt?: string;
  updatedBy?: PageUpdatedBy;
}

export interface PageResponseDataObject {
  attributes?: Page;
  id?: number;
}

export interface PageResponse {
  data?: PageResponseDataObject;
  meta?: PageResponseMeta;
}

export type PageUpdatedByDataAttributes = { [key: string]: any };

export type PageUpdatedByData = {
  attributes?: PageUpdatedByDataAttributes;
  id?: number;
};

export type PageUpdatedBy = {
  data?: PageUpdatedByData;
};

export type PageTeaserImageData = {
  attributes?: PageTeaserImageDataAttributes;
  id?: number;
};

export type PageTeaserImage = {
  data?: PageTeaserImageData;
};

export type PageTeaserImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type PageTeaserImageDataAttributesUpdatedByData = {
  attributes?: PageTeaserImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type PageTeaserImageDataAttributesUpdatedBy = {
  data?: PageTeaserImageDataAttributesUpdatedByData;
};

export type PageTeaserImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: PageTeaserImageDataAttributesCreatedBy;
  ext?: string;
  folder?: PageTeaserImageDataAttributesFolder;
  folderPath?: string;
  formats?: PageTeaserImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: PageTeaserImageDataAttributesProviderMetadata;
  related?: PageTeaserImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: PageTeaserImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type PageTeaserImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type PageTeaserImageDataAttributesRelatedDataItem = {
  attributes?: PageTeaserImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type PageTeaserImageDataAttributesRelated = {
  data?: PageTeaserImageDataAttributesRelatedDataItem[];
};

export type PageTeaserImageDataAttributesProviderMetadata = {};

export type PageTeaserImageDataAttributesFormats = {};

export type PageTeaserImageDataAttributesFolder = {
  data?: PageTeaserImageDataAttributesFolderData;
};

export type PageTeaserImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type PageTeaserImageDataAttributesFolderData = {
  attributes?: PageTeaserImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type PageTeaserImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type PageTeaserImageDataAttributesCreatedByData = {
  attributes?: PageTeaserImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type PageTeaserImageDataAttributesCreatedBy = {
  data?: PageTeaserImageDataAttributesCreatedByData;
};

export type PageLocalizations = {
  data?: PageListResponseDataItemLocalized[];
};

export type PageDefaultHeader = typeof PageDefaultHeader[keyof typeof PageDefaultHeader];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageDefaultHeader = {
  Visible: 'Visible',
  Hidden: 'Hidden',
} as const;

export type PageCreatedByDataAttributes = { [key: string]: any };

export type PageCreatedByData = {
  attributes?: PageCreatedByDataAttributes;
  id?: number;
};

export type PageCreatedBy = {
  data?: PageCreatedByData;
};

export type PageContentItem = SharedBannerFullComponent | SharedHeaderComponent | SharedBannerCardsComponent | SharedBannerVideoComponent | SharedBannerTilesComponent;

export type PageListResponseMetaPagination = {
  page?: number;
  pageCount?: number;
  pageSize?: number;
  total?: number;
};

export type PageListResponseMeta = {
  pagination?: PageListResponseMetaPagination;
};

export interface PageListResponseDataItem {
  attributes?: Page;
  id?: number;
}

export interface PageListResponse {
  data?: PageListResponseDataItem[];
  meta?: PageListResponseMeta;
}

export type PageLocalizationListResponseMetaPagination = {
  page?: number;
  pageCount?: number;
  pageSize?: number;
  total?: number;
};

export type PageLocalizationListResponseMeta = {
  pagination?: PageLocalizationListResponseMetaPagination;
};

export interface PageListResponseDataItemLocalized {
  attributes?: Page;
  id?: number;
}

export interface PageLocalizationListResponse {
  data?: PageListResponseDataItemLocalized[];
  meta?: PageLocalizationListResponseMeta;
}

export type PageLocalizationResponseMeta = { [key: string]: any };

export interface PageResponseDataObjectLocalized {
  attributes?: Page;
  id?: number;
}

export interface PageLocalizationResponse {
  data?: PageResponseDataObjectLocalized;
  meta?: PageLocalizationResponseMeta;
}

export type PageRequestDataTeaserImage = number | string;

export type PageRequestDataDefaultHeader = typeof PageRequestDataDefaultHeader[keyof typeof PageRequestDataDefaultHeader];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageRequestDataDefaultHeader = {
  Visible: 'Visible',
  Hidden: 'Hidden',
} as const;

export type PageRequestDataContentItem = SharedBannerFullComponent | SharedHeaderComponent | SharedBannerCardsComponent | SharedBannerVideoComponent | SharedBannerTilesComponent;

export type PageRequestData = {
  content?: PageRequestDataContentItem[];
  defaultHeader: PageRequestDataDefaultHeader;
  description?: string;
  locale?: string;
  slug: string;
  teaserImage: PageRequestDataTeaserImage;
  title: string;
};

export interface PageRequest {
  data: PageRequestData;
}

export type PageLocalizationRequestTeaserImage = number | string;

export type PageLocalizationRequestDefaultHeader = typeof PageLocalizationRequestDefaultHeader[keyof typeof PageLocalizationRequestDefaultHeader];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageLocalizationRequestDefaultHeader = {
  Visible: 'Visible',
  Hidden: 'Hidden',
} as const;

export type PageLocalizationRequestContentItem = SharedBannerFullComponent | SharedHeaderComponent | SharedBannerCardsComponent | SharedBannerVideoComponent | SharedBannerTilesComponent;

export interface PageLocalizationRequest {
  content?: PageLocalizationRequestContentItem[];
  defaultHeader: PageLocalizationRequestDefaultHeader;
  description?: string;
  locale: string;
  slug: string;
  teaserImage: PageLocalizationRequestTeaserImage;
  title: string;
}

export type ErrorErrorDetails = { [key: string]: any };

export type ErrorError = {
  details?: ErrorErrorDetails;
  message?: string;
  name?: string;
  status?: number;
};

export interface Error {
  data?: ErrorData;
  error: ErrorError;
}

export type ErrorDataOneOfTwoItem = { [key: string]: any };

export type ErrorDataOneOf = { [key: string]: any };

export type ErrorData = ErrorDataOneOf | ErrorDataOneOfTwoItem[] | null;

