/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 2.0.0
 */
export type GetPagesParams = {
/**
 * Sort by attributes ascending (asc) or descending (desc)
 */
sort?: string;
/**
 * Return page/pageSize (default: true)
 */
'pagination[withCount]'?: boolean;
/**
 * Page number (default: 0)
 */
'pagination[page]'?: number;
/**
 * Page size (default: 25)
 */
'pagination[pageSize]'?: number;
/**
 * Offset value (default: 0)
 */
'pagination[start]'?: number;
/**
 * Number of entities to return (default: 25)
 */
'pagination[limit]'?: number;
/**
 * Fields to return (ex: title,author)
 */
fields?: string;
/**
 * Relations to return
 */
populate?: string;
/**
 * Filters to apply
 */
filters?: { [key: string]: any };
/**
 * Locale to apply
 */
locale?: string;
};

export interface SharedBannerVideoComponent {
  __component?: string;
  description?: string;
  id?: number;
  title?: string;
  videoUrl?: string;
}

export type PrivatePageRelationComponentPageDataAttributes = { [key: string]: any };

export type PrivatePageRelationComponentPageData = {
  attributes?: PrivatePageRelationComponentPageDataAttributes;
  id?: number;
};

export type PrivatePageRelationComponentPage = {
  data?: PrivatePageRelationComponentPageData;
};

export type PrivatePageRelationComponentColor = typeof PrivatePageRelationComponentColor[keyof typeof PrivatePageRelationComponentColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrivatePageRelationComponentColor = {
  Default: 'Default',
  Marked: 'Marked',
} as const;

export interface PrivatePageRelationComponent {
  Color?: PrivatePageRelationComponentColor;
  id?: number;
  page?: PrivatePageRelationComponentPage;
}

export interface SharedBannerTilesComponent {
  __component?: string;
  id?: number;
  teasers?: PrivatePageRelationComponent[];
}

export interface SharedBannerCardsComponent {
  __component?: string;
  id?: number;
  teasers?: PrivatePageRelationComponent[];
}

export type SharedHeaderComponentImageData = {
  attributes?: SharedHeaderComponentImageDataAttributes;
  id?: number;
};

export type SharedHeaderComponentImage = {
  data?: SharedHeaderComponentImageData;
};

export interface SharedHeaderComponent {
  __component?: string;
  buttons?: SharedButtonComponent[];
  id?: number;
  image?: SharedHeaderComponentImage;
  title?: string;
}

export type SharedHeaderComponentImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedHeaderComponentImageDataAttributesUpdatedByData = {
  attributes?: SharedHeaderComponentImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedHeaderComponentImageDataAttributesUpdatedBy = {
  data?: SharedHeaderComponentImageDataAttributesUpdatedByData;
};

export type SharedHeaderComponentImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedHeaderComponentImageDataAttributesRelatedDataItem = {
  attributes?: SharedHeaderComponentImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedHeaderComponentImageDataAttributesRelated = {
  data?: SharedHeaderComponentImageDataAttributesRelatedDataItem[];
};

export type SharedHeaderComponentImageDataAttributesProviderMetadata = {};

export type SharedHeaderComponentImageDataAttributesFormats = {};

export type SharedHeaderComponentImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedHeaderComponentImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedHeaderComponentImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedHeaderComponentImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedHeaderComponentImageDataAttributesProviderMetadata;
  related?: SharedHeaderComponentImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedHeaderComponentImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedHeaderComponentImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedHeaderComponentImageDataAttributesFolderData = {
  attributes?: SharedHeaderComponentImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedHeaderComponentImageDataAttributesFolder = {
  data?: SharedHeaderComponentImageDataAttributesFolderData;
};

export type SharedHeaderComponentImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedHeaderComponentImageDataAttributesCreatedByData = {
  attributes?: SharedHeaderComponentImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedHeaderComponentImageDataAttributesCreatedBy = {
  data?: SharedHeaderComponentImageDataAttributesCreatedByData;
};

export type SharedBannerComponentType = typeof SharedBannerComponentType[keyof typeof SharedBannerComponentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerComponentType = {
  Card: 'Card',
  Tile: 'Tile',
  Icon: 'Icon',
  'Half-Half': 'Half-Half',
} as const;

export type SharedButtonComponentType = typeof SharedButtonComponentType[keyof typeof SharedButtonComponentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedButtonComponentType = {
  card: 'card',
  tile: 'tile',
  icon: 'icon',
} as const;

export type SharedButtonComponentLinkDataAttributes = { [key: string]: any };

export type SharedButtonComponentLinkData = {
  attributes?: SharedButtonComponentLinkDataAttributes;
  id?: number;
};

export type SharedButtonComponentLink = {
  data?: SharedButtonComponentLinkData;
};

export type SharedButtonComponentImageData = {
  attributes?: SharedButtonComponentImageDataAttributes;
  id?: number;
};

export type SharedButtonComponentImage = {
  data?: SharedButtonComponentImageData;
};

export interface SharedButtonComponent {
  color?: SharedButtonComponentColor;
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedButtonComponentImage;
  link?: SharedButtonComponentLink;
  title?: string;
  type?: SharedButtonComponentType;
}

export interface SharedBannerComponent {
  __component?: string;
  content?: SharedButtonComponent[];
  id?: number;
  type?: SharedBannerComponentType;
}

export type SharedButtonComponentImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedButtonComponentImageDataAttributesUpdatedByData = {
  attributes?: SharedButtonComponentImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedButtonComponentImageDataAttributesUpdatedBy = {
  data?: SharedButtonComponentImageDataAttributesUpdatedByData;
};

export type SharedButtonComponentImageDataAttributesRelatedDataItem = {
  attributes?: SharedButtonComponentImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedButtonComponentImageDataAttributesRelated = {
  data?: SharedButtonComponentImageDataAttributesRelatedDataItem[];
};

export type SharedButtonComponentImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedButtonComponentImageDataAttributesProviderMetadata = {};

export type SharedButtonComponentImageDataAttributesFormats = {};

export type SharedButtonComponentImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedButtonComponentImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedButtonComponentImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedButtonComponentImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedButtonComponentImageDataAttributesProviderMetadata;
  related?: SharedButtonComponentImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedButtonComponentImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedButtonComponentImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedButtonComponentImageDataAttributesFolderData = {
  attributes?: SharedButtonComponentImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedButtonComponentImageDataAttributesFolder = {
  data?: SharedButtonComponentImageDataAttributesFolderData;
};

export type SharedButtonComponentImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedButtonComponentImageDataAttributesCreatedByData = {
  attributes?: SharedButtonComponentImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedButtonComponentImageDataAttributesCreatedBy = {
  data?: SharedButtonComponentImageDataAttributesCreatedByData;
};

export type SharedButtonComponentColor = typeof SharedButtonComponentColor[keyof typeof SharedButtonComponentColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedButtonComponentColor = {
  Default: 'Default',
  Marked: 'Marked',
} as const;

export type SharedBannerFullComponentLinkDataAttributes = {
  content?: SharedBannerFullComponentLinkDataAttributesContentItem[];
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesCreatedBy;
  defaultHeader?: SharedBannerFullComponentLinkDataAttributesDefaultHeader;
  description?: string;
  locale?: string;
  localizations?: SharedBannerFullComponentLinkDataAttributesLocalizations;
  publishedAt?: string;
  slug?: string;
  teaserImage?: SharedBannerFullComponentLinkDataAttributesTeaserImage;
  title?: string;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesUpdatedBy;
};

export type SharedBannerFullComponentLinkData = {
  attributes?: SharedBannerFullComponentLinkDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLink = {
  data?: SharedBannerFullComponentLinkData;
};

export interface SharedBannerFullComponent {
  __component?: string;
  alignment?: SharedBannerFullComponentAlignment;
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedBannerFullComponentImage;
  link?: SharedBannerFullComponentLink;
  title?: string;
}

export type SharedBannerFullComponentLinkDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImage = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageData;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesTeaserImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesLocalizationsDataItem = {};

export type SharedBannerFullComponentLinkDataAttributesLocalizations = {
  data?: SharedBannerFullComponentLinkDataAttributesLocalizationsDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesDefaultHeader = typeof SharedBannerFullComponentLinkDataAttributesDefaultHeader[keyof typeof SharedBannerFullComponentLinkDataAttributesDefaultHeader];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesDefaultHeader = {
  Visible: 'Visible',
  Hidden: 'Hidden',
} as const;

export type SharedBannerFullComponentLinkDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItem = {
  Color?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemColor;
  id?: number;
  page?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemPage;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenine = {
  __component?: string;
  id?: number;
  teasers?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemPageDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemPageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemPageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemPage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemPageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemColor = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemColor[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenineTeasersItemColor = {
  Default: 'Default',
  Marked: 'Marked',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneoneeight = {
  __component?: string;
  description?: string;
  id?: number;
  title?: string;
  videoUrl?: string;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemPageDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemPageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemPageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemPage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemPageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemColor = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemColor[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemColor = {
  Default: 'Default',
  Marked: 'Marked',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItem = {
  Color?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemColor;
  id?: number;
  page?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItemPage;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwo = {
  __component?: string;
  id?: number;
  teasers?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwoTeasersItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenone = {
  __component?: string;
  buttons?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItem[];
  id?: number;
  image?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImage;
  title?: string;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemType = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemType[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemType = {
  card: 'card',
  tile: 'tile',
  icon: 'icon',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemLinkDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemLinkData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemLinkDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemLink = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemLinkData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItem = {
  color?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemColor;
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImage;
  link?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemLink;
  title?: string;
  type?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemType;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemColor = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemColor[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenoneButtonsItemColor = {
  Default: 'Default',
  Marked: 'Marked',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightType = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightType[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightType = {
  card: 'card',
  tile: 'tile',
  icon: 'icon',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureight = {
  __component?: string;
  color?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightColor;
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImage;
  link?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightLink;
  title?: string;
  type?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightType;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightLinkDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightLinkData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightLinkDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightLink = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightLinkData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightColor = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightColor[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureightColor = {
  Default: 'Default',
  Marked: 'Marked',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeType = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeType[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeType = {
  Card: 'Card',
  Tile: 'Tile',
  Icon: 'Icon',
  'Half-Half': 'Half-Half',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemType = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemType[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemType = {
  card: 'card',
  tile: 'tile',
  icon: 'icon',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItem = {
  color?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemColor;
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImage;
  link?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemLink;
  title?: string;
  type?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemType;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothree = {
  __component?: string;
  content?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItem[];
  id?: number;
  type?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeType;
};

export type SharedBannerFullComponentLinkDataAttributesContentItem = SharedBannerFullComponentLinkDataAttributesContentItemAnyOf | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothree | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfFoureight | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfSevenone | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonetwo | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneoneeight | SharedBannerFullComponentLinkDataAttributesContentItemAnyOfOneonenine;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemLinkDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemLinkData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemLinkDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemLink = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemLinkData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemColor = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemColor[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfTwothreeContentItemColor = {
  Default: 'Default',
  Marked: 'Marked',
} as const;

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOf = {
  __component?: string;
  alignment?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment;
  description?: string;
  externalUrl?: string;
  id?: number;
  image?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImage;
  link?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLink;
  title?: string;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLinkDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLinkData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLinkDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLink = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfLinkData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImage = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelated = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFormats = {};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolder = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesFolderData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentLinkDataAttributesContentItemAnyOfImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment = typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment[keyof typeof SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentLinkDataAttributesContentItemAnyOfAlignment = {
  Left: 'Left',
  Middle: 'Middle',
  Right: 'Right',
} as const;

export type SharedBannerFullComponentImageData = {
  attributes?: SharedBannerFullComponentImageDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImage = {
  data?: SharedBannerFullComponentImageData;
};

export type SharedBannerFullComponentImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesRelated = {
  data?: SharedBannerFullComponentImageDataAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentImageDataAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentImageDataAttributesProviderMetadata;
  related?: SharedBannerFullComponentImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesProviderMetadata = {};

export type SharedBannerFullComponentImageDataAttributesFormats = {};

export type SharedBannerFullComponentImageDataAttributesFolderData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolder = {
  data?: SharedBannerFullComponentImageDataAttributesFolderData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributes = {
  children?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildren;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedBy;
  files?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFiles;
  name?: string;
  parent?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesParent;
  path?: string;
  pathId?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesUpdatedBy;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesParentDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesParentData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesParentDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesParent = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesParentData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFiles = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelatedDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelatedDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelatedDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelated = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelatedDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesProviderMetadata = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFormats = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolderDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolderData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolderDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolder = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolderData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributes = {
  blocked?: boolean;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy;
  email?: string;
  firstname?: string;
  isActive?: boolean;
  lastname?: string;
  preferedLanguage?: string;
  registrationToken?: string;
  resetPasswordToken?: string;
  roles?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy;
  username?: string;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy;
  ext?: string;
  folder?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  formats?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesProviderMetadata;
  related?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributes = {
  code?: string;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedBy;
  description?: string;
  name?: string;
  permissions?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissions;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedBy;
  users?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsers;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsersDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsersDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsersDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsers = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUsersDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissions = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesProperties = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesConditions = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesActionParameters = {};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributes = {
  action?: string;
  actionParameters?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesActionParameters;
  conditions?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesConditions;
  createdAt?: string;
  createdBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy;
  properties?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesProperties;
  role?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole;
  subject?: string;
  updatedAt?: string;
  updatedBy?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesCreatedByData;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildrenDataItemAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildrenDataItem = {
  attributes?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildrenDataItemAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildren = {
  data?: SharedBannerFullComponentImageDataAttributesFolderDataAttributesChildrenDataItem[];
};

export type SharedBannerFullComponentImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type SharedBannerFullComponentImageDataAttributesCreatedByData = {
  attributes?: SharedBannerFullComponentImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type SharedBannerFullComponentImageDataAttributesCreatedBy = {
  data?: SharedBannerFullComponentImageDataAttributesCreatedByData;
};

export type SharedBannerFullComponentAlignment = typeof SharedBannerFullComponentAlignment[keyof typeof SharedBannerFullComponentAlignment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SharedBannerFullComponentAlignment = {
  Left: 'Left',
  Middle: 'Middle',
  Right: 'Right',
} as const;

export type PageResponseMeta = { [key: string]: any };

export interface PageResponseDataObject {
  attributes?: Page;
  id?: number;
}

export interface PageResponse {
  data?: PageResponseDataObject;
  meta?: PageResponseMeta;
}

export type PageUpdatedByDataAttributes = { [key: string]: any };

export type PageUpdatedByData = {
  attributes?: PageUpdatedByDataAttributes;
  id?: number;
};

export type PageUpdatedBy = {
  data?: PageUpdatedByData;
};

export interface Page {
  content?: PageContentItem[];
  createdAt?: string;
  createdBy?: PageCreatedBy;
  defaultHeader: PageDefaultHeader;
  description?: string;
  locale?: string;
  localizations?: PageLocalizations;
  publishedAt?: string;
  slug: string;
  teaserImage: PageTeaserImage;
  title: string;
  updatedAt?: string;
  updatedBy?: PageUpdatedBy;
}

export type PageTeaserImageDataAttributesUpdatedByDataAttributes = { [key: string]: any };

export type PageTeaserImageDataAttributesUpdatedByData = {
  attributes?: PageTeaserImageDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type PageTeaserImageDataAttributesUpdatedBy = {
  data?: PageTeaserImageDataAttributesUpdatedByData;
};

export type PageTeaserImageDataAttributes = {
  alternativeText?: string;
  caption?: string;
  createdAt?: string;
  createdBy?: PageTeaserImageDataAttributesCreatedBy;
  ext?: string;
  folder?: PageTeaserImageDataAttributesFolder;
  folderPath?: string;
  formats?: PageTeaserImageDataAttributesFormats;
  hash?: string;
  height?: number;
  mime?: string;
  name?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: PageTeaserImageDataAttributesProviderMetadata;
  related?: PageTeaserImageDataAttributesRelated;
  size?: number;
  updatedAt?: string;
  updatedBy?: PageTeaserImageDataAttributesUpdatedBy;
  url?: string;
  width?: number;
};

export type PageTeaserImageData = {
  attributes?: PageTeaserImageDataAttributes;
  id?: number;
};

export type PageTeaserImage = {
  data?: PageTeaserImageData;
};

export type PageTeaserImageDataAttributesRelatedDataItemAttributes = { [key: string]: any };

export type PageTeaserImageDataAttributesRelatedDataItem = {
  attributes?: PageTeaserImageDataAttributesRelatedDataItemAttributes;
  id?: number;
};

export type PageTeaserImageDataAttributesRelated = {
  data?: PageTeaserImageDataAttributesRelatedDataItem[];
};

export type PageTeaserImageDataAttributesProviderMetadata = {};

export type PageTeaserImageDataAttributesFormats = {};

export type PageTeaserImageDataAttributesFolderDataAttributes = { [key: string]: any };

export type PageTeaserImageDataAttributesFolderData = {
  attributes?: PageTeaserImageDataAttributesFolderDataAttributes;
  id?: number;
};

export type PageTeaserImageDataAttributesFolder = {
  data?: PageTeaserImageDataAttributesFolderData;
};

export type PageTeaserImageDataAttributesCreatedByDataAttributes = { [key: string]: any };

export type PageTeaserImageDataAttributesCreatedByData = {
  attributes?: PageTeaserImageDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type PageTeaserImageDataAttributesCreatedBy = {
  data?: PageTeaserImageDataAttributesCreatedByData;
};

export type PageLocalizations = {
  data?: PageListResponseDataItemLocalized[];
};

export type PageDefaultHeader = typeof PageDefaultHeader[keyof typeof PageDefaultHeader];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageDefaultHeader = {
  Visible: 'Visible',
  Hidden: 'Hidden',
} as const;

export type PageCreatedByDataAttributes = { [key: string]: any };

export type PageCreatedByData = {
  attributes?: PageCreatedByDataAttributes;
  id?: number;
};

export type PageCreatedBy = {
  data?: PageCreatedByData;
};

export type PageContentItem = SharedBannerFullComponent | SharedBannerComponent | SharedButtonComponent | SharedHeaderComponent | SharedBannerCardsComponent | SharedBannerVideoComponent | SharedBannerTilesComponent;

export type PageListResponseMetaPagination = {
  page?: number;
  pageCount?: number;
  pageSize?: number;
  total?: number;
};

export type PageListResponseMeta = {
  pagination?: PageListResponseMetaPagination;
};

export interface PageListResponseDataItem {
  attributes?: Page;
  id?: number;
}

export interface PageListResponse {
  data?: PageListResponseDataItem[];
  meta?: PageListResponseMeta;
}

export type PageLocalizationListResponseMetaPagination = {
  page?: number;
  pageCount?: number;
  pageSize?: number;
  total?: number;
};

export type PageLocalizationListResponseMeta = {
  pagination?: PageLocalizationListResponseMetaPagination;
};

export interface PageListResponseDataItemLocalized {
  attributes?: Page;
  id?: number;
}

export interface PageLocalizationListResponse {
  data?: PageListResponseDataItemLocalized[];
  meta?: PageLocalizationListResponseMeta;
}

export type PageLocalizationResponseMeta = { [key: string]: any };

export interface PageResponseDataObjectLocalized {
  attributes?: Page;
  id?: number;
}

export interface PageLocalizationResponse {
  data?: PageResponseDataObjectLocalized;
  meta?: PageLocalizationResponseMeta;
}

export type PageRequestDataTeaserImage = number | string;

export type PageRequestDataDefaultHeader = typeof PageRequestDataDefaultHeader[keyof typeof PageRequestDataDefaultHeader];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageRequestDataDefaultHeader = {
  Visible: 'Visible',
  Hidden: 'Hidden',
} as const;

export type PageRequestDataContentItem = SharedBannerFullComponent | SharedBannerComponent | SharedButtonComponent | SharedHeaderComponent | SharedBannerCardsComponent | SharedBannerVideoComponent | SharedBannerTilesComponent;

export type PageRequestData = {
  content?: PageRequestDataContentItem[];
  defaultHeader: PageRequestDataDefaultHeader;
  description?: string;
  locale?: string;
  slug: string;
  teaserImage: PageRequestDataTeaserImage;
  title: string;
};

export interface PageRequest {
  data: PageRequestData;
}

export type PageLocalizationRequestTeaserImage = number | string;

export type PageLocalizationRequestDefaultHeader = typeof PageLocalizationRequestDefaultHeader[keyof typeof PageLocalizationRequestDefaultHeader];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageLocalizationRequestDefaultHeader = {
  Visible: 'Visible',
  Hidden: 'Hidden',
} as const;

export type PageLocalizationRequestContentItem = SharedBannerFullComponent | SharedBannerComponent | SharedButtonComponent | SharedHeaderComponent | SharedBannerCardsComponent | SharedBannerVideoComponent | SharedBannerTilesComponent;

export interface PageLocalizationRequest {
  content?: PageLocalizationRequestContentItem[];
  defaultHeader: PageLocalizationRequestDefaultHeader;
  description?: string;
  locale: string;
  slug: string;
  teaserImage: PageLocalizationRequestTeaserImage;
  title: string;
}

export type ErrorErrorDetails = { [key: string]: any };

export type ErrorError = {
  details?: ErrorErrorDetails;
  message?: string;
  name?: string;
  status?: number;
};

export interface Error {
  data?: ErrorData;
  error: ErrorError;
}

export type ErrorDataOneOfTwoItem = { [key: string]: any };

export type ErrorDataOneOf = { [key: string]: any };

export type ErrorData = ErrorDataOneOf | ErrorDataOneOfTwoItem[] | null;

