name: Claude Auto Review with Tracking
on:
    pull_request:
        types: [opened, synchronize, ready_for_review, reopened]

jobs:
    delete-old-claude-comments:
        # Currently, the claude-code-action does not support updating its own comments.
        # https://github.com/anthropics/claude-code-action/issues/37
        name: Delete old Claude comments
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write

        steps:
            - name: Clean up old comments
              uses: actions/github-script@v7
              with:
                  script: |
                      const params = { issue_number: context.issue.number, owner: context.repo.owner, repo: context.repo.repo }
                      const comments = await github.rest.issues.listComments(params);

                      for (const comment of comments.data) {
                        if (comment.user.login === 'claude[bot]') {
                          await github.rest.issues.deleteComment({ ...params, comment_id: comment.id });
                        }
                      }

    review:
        needs: delete-old-claude-comments
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - uses: anthropics/claude-code-action@v1
              with:
                  claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
                  track_progress: true # ✨ Enables tracking comments
                  
                  prompt: |
                      REPO: ${{ github.repository }}
                      PR NUMBER: ${{ github.event.pull_request.number }}

                      Please review this pull request with a focus on:
                      - Code quality and best practices
                      - Potential bugs or issues
                      - Security implications
                      - Performance considerations

                      Provide detailed feedback using inline comments for specific issues.
                      Don't provide comments/feedback when everything is fine. We don't need positive comments. 
                      Only provide comments when there are issues.

                  claude_args: |
                      --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)"
